version: '3.3'

volumes:
  app-data:

services:
  app:
    container_name: laravel-test-app
    # fpm port 9000
    build:
      dockerfile: ./docker/app/Dockerfile
      context: .
    volumes:
      - "./:/app"
    depends_on:
      - db

  nginx:
    container_name: laravel-test-nginx
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - "./docker/nginx/app.conf:/etc/nginx/conf.d/default.conf"
      - "./public:/app/public"
    depends_on:
      - app

  db:
    container_name: laravel-test-db
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3307:3306"
    volumes:
      - "app-data:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: "example"
      MYSQL_USER: "example"
      MYSQL_PASSWORD: "example"
      MYSQL_ROOT_PASSWORD: "example"
